### PR TITLE
revert: remove demo

### PR DESCRIPTION
**Pull request by jcbhmr**
couldn't really find an appropriate conventional commit category in
https://github.com/pvdlg/conventional-changelog-metahub#commit-types or
https://cheatography.com/albelop/cheat-sheets/conventional-commits/ 🤔

this pr would...
- [x] remove the hello demo template image
- [x] remove the color demo template image
- [x] remove them from the test list in test-pr.yml

since I don't think we've run the release github action workflow manually yet, these are still un-published as of now

### CODE REVIEW

**Comment by jcbhmr** [comment]
i guess "revert" jumped out as the best of these
image

**Comment by eitsupi** [comment]
Thanks for working on this. I think if we merge #5 first, we won't have to do any extra hacks to the filter.

**Comment by jcbhmr** [comment]
> Thanks for working on this. I think if we merge #5 first, we won't have to do any extra hacks to the filter.

👍 sounds good!

**Comment by eitsupi** [comment]
Once this is merged, let's run the publish workflow. (I pressed the wrong button earlier, but cancelled it)

**Comment by eitsupi** [comment]
You seem to have forgotten to update the filter.

**Comment by jcbhmr** [comment]
youre right. i did the filter editing in a direct commit to main. https://github.com/devcontainers-community/templates/commit/48100e000b957d8451ba7612d70f93657fe794ce

this was an oopsie on my part! 😬

**Pull request merged**
