### PR TITLE
refactor: move test to root test.sh script

### LINKED ISSUE #3: Move smoke test into standalone script that can be run locally
It would be nice to be able to run tests locally to make sure everything "kinda works". Right now I don't _think_ this is possible.

- [ ] Create some kind of `tools/test.sh` file
- [ ] Move logic from https://github.com/devcontainers-community/templates/tree/main/.github/actions/smoke-test to there
- [ ] Make sure it still works
- [ ] Add a GitHub Action to test changes

### PR DESCRIPTION
**Pull request by jcbhmr**
Based heavily on https://github.com/devcontainers/template-starter/pull/16/commits/a72eea935d8c7d41e4cbd3d021dc7a5c8771b19d

this pr would...
- [x] remove the smoke test action in the .github/actions folder
- [x] add a test.sh root script
- [x] make sure the test-pr action still works
- [x] make shellcheck happy
- [x] add test instructions to readme

fixes #3

### CODE REVIEW

**Comment by jcbhmr** [comment]
do you think i need to fix the shellcheck stuff, or should I just leave it? i think I should probably fix it 😆

**Comment by jcbhmr** [comment]
actually before im ready to merge i also need to update the readme. and fix the shellcheck stuff. jumped the gun a bit! oops😬

**Comment by jcbhmr** [comment]
I was going to try and make it into a more legible and hopefully maintainable Python script, but I decided to just accept the bad shellcheck linting stuff on the script copied from https://github.com/devcontainers/template-starter/blob/a72eea935d8c7d41e4cbd3d021dc7a5c8771b19d/.github/workflows/smoke-test/test.sh

🤷‍♀️

**Comment by jcbhmr** [comment]
Here's what `./test.sh jupyter-datascience-notebooks` got me:

image

it works! ✅

yes, shellcheck is going to fail on megalinter. oh well. I was going to try and make it into a more legible and hopefully maintainable Python script, but I decided to just accept the bad shellcheck linting stuff on the script copied from https://github.com/devcontainers/template-starter/blob/a72eea935d8c7d41e4cbd3d021dc7a5c8771b19d/.github/workflows/smoke-test/test.sh

**Comment by eitsupi** [comment]
Thanks for working on this.
Merge later after correcting for Linter errors.

**Comment by eitsupi** [comment]
@jcbhmr I updated the script but not sure it works. Could you test the script?

**Comment by jcbhmr** [comment]
@eitsupi seems to work! 👍

image

**Review by eitsupi — APPROVED** [review]

**Pull request merged**
